### ISSUE TITLE
How to namespace docready?

### ISSUE THREAD

**Issue by RavenHursT** [jfriend00/docReady#4]
You have this at the top of your library:

```javascript
// The public function name defaults to window.docReady
    // but you can pass in your own object and own function name and those will be used
    // if you want to put them in a different namespace
```
But I don't see anything in your documentation as to how to implement this.  Can you give some instructions?

**Comment by jfriend00** [comment]
In this line at the very end of the code:
```
})("docReady", window);
```
You can pass in your own object and method name and the function will be assigned as that method on that object:

```
var myNamespace = {};
myNamspace.myMethod = function() {...};

(function(funcName, baseObj) {
....
})("docReady", myNamespace);
```

Then, you would call docReady like this:

```
myNamespace.docReady(function() {
   ...
});
```

**Comment by jfriend00** [comment]
More comments added to the source code to document this issue.

**Comment by RavenHursT** [comment]
Ah.. so you'd have to modify the source code to make this happen, I get it now.

Would probably be a good future feature to add an api that allows you to do something like this w/o having to modify the library directly right?

**Comment by jfriend00** [comment]
You can do that yourself already by just putting this code after the docReady code.

```
myNameSpace.myMethod = docReady;
delete window.docReady;
```

**Comment by RavenHursT** [comment]
Ah... well now that was easy.. thanks!
